#!/usr/bin/env bash
# Hermetic environment regressions. No live Docker, SQL, HTTP or process access.
set -euo pipefail
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
# Retain fixtures when requested so the controller can audit exact inputs/logs.
trap '[ "${MULTICA_KEEP_TEST_FIXTURES:-0}" = 1 ] || rm -rf "$tmp_dir"' EXIT
export HOME="$tmp_dir/home" MULTICA_DEV_HOME="$tmp_dir/registry" MULTICA_DEV_TMPDIR="$tmp_dir/tmp"
export MULTICA_DEV_PROFILES_HOME="$tmp_dir/profiles" MULTICA_DEV_WORKSPACES_PARENT="$tmp_dir/workspaces"
export MULTICA_DEV_DESKTOP_APP_DATA="$tmp_dir/appdata" FIXTURE_MISSES="$tmp_dir/misses"
mkdir -p "$HOME" "$tmp_dir/bin"
for tool in docker curl psql go make pnpm lsof ps; do
  printf '#!/usr/bin/env bash
echo %s >> "$FIXTURE_MISSES"
exit 97
' "$tool" > "$tmp_dir/bin/$tool"
  chmod +x "$tmp_dir/bin/$tool"
done
# Pure utilities are explicit; the fixture never falls through to a user PATH.
for tool in bash dirname tr mkdir rm date chmod sed cat tail basename uname id grep cp ln; do
  ln -s "$(command -v "$tool")" "$tmp_dir/bin/$tool"
done
ln -s "$(command -v node)" "$tmp_dir/bin/node"
export PATH="$tmp_dir/bin"
mkdir -p "$tmp_dir/source/scripts"
cp "$root_dir/scripts/dev-env.sh" "$tmp_dir/source/scripts/dev-env.sh"
fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "PASS: $*"; }
echo "Owned fixture tree: $tmp_dir"
# Break: validating each component only after stopping earlier components shuts
# down the API even when a later requested component is invalid.
status=0
(
  source "$tmp_dir/source/scripts/dev-env.sh"
  resolve_env_for_read() { NAME=fixture; BACKEND_PORT=18080; FRONTEND_PORT=13000; DATABASE_URL=fixture; DB_NAME=fixture; }
  stop_component() { printf '%s\n' "$1" >> "$tmp_dir/stops"; }
  cmd_down --components api,nope
) > "$tmp_dir/unknown-down.log" 2>&1 || status=$?
[ "$status" -ne 0 ] || fail 'unknown component accepted'
[ ! -s "$tmp_dir/stops" ] || fail 'TestUnknownComponentDeniedBeforeAPIStop: API stopped before validation'
pass TestUnknownComponentDeniedBeforeAPIStop
[ ! -s "$FIXTURE_MISSES" ] || fail 'unmatched external fixture'
# Each case gets its own source copy, private inputs and trapped PATH.
node - "$root_dir" "$tmp_dir" <<'NODE'
const fs=require('fs'),path=require('path'),cp=require('child_process');
const source=process.argv[2],temp=fs.realpathSync(process.argv[3]),node=process.execPath;
let passed=0,failed=0;
function check(ok,msg){if(!ok)throw Error(msg);}
function test(name,fn){try{fn();console.log('PASS: '+name);passed++;}catch(e){console.log('FAIL: '+name+': '+e.message);failed++;}}
function fixture(name="fixture"){
 const dir=fs.mkdtempSync(path.join(temp,'case-')),repo=path.join(dir,'source'),state=path.join(dir,'registry',name),home=path.join(dir,'home'),bin=path.join(dir,'bin'),log=path.join(dir,'actions');
 for(const p of [repo,path.join(repo,'scripts'),path.join(repo,'server'),state,home,bin])fs.mkdirSync(p,{recursive:true,mode:0o700});fs.writeFileSync(log,'');
 for(const p of ['scripts/fleet-env.sh','scripts/dev-env.sh','docker-compose.fleet.yml','Makefile'])if(fs.existsSync(path.join(source,p)))fs.copyFileSync(path.join(source,p),path.join(repo,p));
 const privateFile=(name,value)=>{const p=path.join(dir,name);fs.writeFileSync(p,typeof value==='string'?value:JSON.stringify(value),{mode:0o600});return p;};
 const profile=privateFile('profile.json',{api_key:'fixture',base_url:'https://provider.invalid',model:'fixture'}),profiles=privateFile('profiles.json',{version:1,owners:{'11111111-1111-4111-8111-111111111111':profile}}),key=privateFile('service-key','k'.repeat(64));
 const digest='@sha256:'+'a'.repeat(64);
 const input=privateFile('approved.json',{version:1,database_name:'worktree_test',database_lifecycle:'exclusive-managed',context:'fixture-engine',engine_id:'engine-id',pg_container_id:'pg-id',pg_network_id:'pg-net-id',pg_alias:'postgres',pg_port:5432,pg_host_port:15432,socket_path:'/var/run/docker.sock',uid:process.getuid(),gid:process.getgid(),socket_gid:0,node_image:'node'+digest,fleet_image:'fleet'+digest,api_url:'http://host.docker.internal:18401',profiles_file:profiles,service_key_file:key,aurora:{server_url:'https://multica.example.com',anthropic_base_url:'',anthropic_model:'',claude_env:{'ANTHROPIC_DEFAULT_SONNET_MODEL':'glm-5.3-flash[1M]','API_TIMEOUT_MS':'600000'}}});
 const db='postgresql://u%40ser:p%40ss%2Fword@127.0.0.1:15432/worktree%5Ftest?sslmode=disable&application_name=fleet%20test&connect_timeout=3';
 const env={PATH:bin,HOME:home,PGSSLCERT:path.join(home,'bad.crt'),PGPASSFILE:path.join(home,'pass-fifo'),FIXTURE_LOG:log,FIXTURE_INPUT:input};
 fs.writeFileSync(env.PGSSLCERT,'malformed certificate');cp.execFileSync('/usr/bin/mkfifo',[env.PGPASSFILE]);fs.mkdirSync(path.join(home,'.postgresql'),{mode:0o700});cp.execFileSync('/usr/bin/mkfifo',[path.join(home,'.postgresql','postgresql.crt')]);fs.writeFileSync(path.join(home,'.postgresql','postgresql.key'),'malformed key');fs.symlinkSync(node,path.join(bin,'node'));
 for(const name of ['dirname','tr','mkdir','rm','date','chmod','sed','cat','tail','basename','uname','id','grep'])fs.symlinkSync(cp.execFileSync('/usr/bin/which',[name],{encoding:'utf8'}).trim(),path.join(bin,name));fs.symlinkSync('/bin/bash',path.join(bin,'bash'));
 const exe=(name,js)=>fs.writeFileSync(path.join(bin,name),'#!'+node+'\n'+js,{mode:0o700});
 for(const name of ['go','make','pnpm','psql','curl','lsof','ps','claude','codex','hermes','aws'])exe(name,"require('fs').appendFileSync(process.env.FIXTURE_LOG,'UNAPPROVED '+process.argv.slice(2).join(' ')+'\\n');process.exit(97)");
 exe('psql',"require('fs').appendFileSync("+JSON.stringify(log)+",'database identity checked'+String.fromCharCode(10));if(JSON.stringify(process.argv.slice(2))!=="+JSON.stringify(JSON.stringify(['--no-psqlrc','--set=ON_ERROR_STOP=1','--tuples-only','--no-align','--dbname',db,'--command','SELECT current_database()']))+")process.exit(97);console.log('worktree_test');");
 exe('go','const fs=require("fs"),a=process.argv.slice(2);if(a.join(" ")!=="run ./cmd/migrate up"||process.env.DATABASE_URL!=='+JSON.stringify(db)+'){fs.appendFileSync(process.env.FIXTURE_LOG,"UNAPPROVED go\\n");process.exit(97);}fs.appendFileSync(process.env.FIXTURE_LOG,"migration complete\\n");if(fs.existsSync(process.env.FIXTURE_LOG+".migration-fail"))process.exit(1);');
 exe('lsof','const fs=require("fs"),s=JSON.parse(fs.readFileSync(process.env.FIXTURE_LOG+".docker"));if(!process.argv.slice(2).join(" ").startsWith("-nP -iTCP:")){fs.appendFileSync(process.env.FIXTURE_LOG,"UNAPPROVED lsof\\n");process.exit(97);}process.exit(s.port_busy&&process.argv.includes("-iTCP:19321")?0:1);');
 const op=privateFile('operator','#!'+node+'\n'+[
 'const fs=require("fs"),a=process.argv.slice(2),log='+JSON.stringify(log)+';',
 'if(process.env.HOME!==undefined||Object.keys(process.env).some(k=>k.startsWith("PG")))process.exit(96);',
 'const get=k=>a[a.indexOf("--"+k)+1];if(get("database-url")!=='+JSON.stringify(db)+'||!get("operation-key")||!get("namespace")||!get("fleet-id"))process.exit(95);',
 'for(const k of ["config","service-key","profiles"])if(!require("path").isAbsolute(get(k)))process.exit(94);',
 'fs.appendFileSync(log,"operator "+a[0]+"\\n");const sp=log+".operator-state",s=fs.existsSync(sp)?JSON.parse(fs.readFileSync(sp)):{generation:0,closed:false,key:null};',
 'if(a[0]==="resume"){if(fs.existsSync(log+".resume-fail")||s.generation>0&&(!s.closed||s.key!==get("operation-key")))process.exit(1);s.closed=false;s.finalized=false;s.manifest=null;}',
 // This fixture models an empty namespace: no original node refs are synthesized.
 'const validOriginal=()=>{const m=s.manifest;return m!==null&&typeof m==="object"&&!Array.isArray(m)&&Object.keys(m).sort().join() === "action,completions,fleet_id,generation,key,namespace,version"&&m.version===1&&m.namespace===get("namespace")&&m.fleet_id===get("fleet-id")&&Number.isSafeInteger(s.generation)&&s.generation>0&&m.generation===s.generation&&m.key===s.key&&m.action===s.action&&["stop","delete"].includes(m.action)&&Array.isArray(m.completions)&&m.completions.length===0;};',
 'if(["quiesce","destroy"].includes(a[0])){',
 ' if(s.closed&&s.key!==get("operation-key")||!s.closed&&s.generation>0&&s.key===get("operation-key"))process.exit(1);const wanted=a[0]==="destroy"?"delete":"stop";',
 ' if(s.finalized){if(!s.closed||!validOriginal()||fs.existsSync(log+".proof-fail"))process.exit(1);if(s.action===wanted){if(fs.existsSync(log+".busy")&&a[0]==="quiesce")process.exit(1);console.log("fleet-env: "+a[0]+" complete");return;}if(a[0]!=="destroy"||s.action!=="stop")process.exit(1);s.generation++;s.finalized=false;s.manifest=null;}',
 ' if(!s.closed){s.generation++;s.key=get("operation-key");}s.closed=true;if(fs.existsSync(log+".destroy-fail")&&a[0]==="destroy"||fs.existsSync(log+".proof-fail"))process.exit(1);',
 ' s.action=wanted;s.finalized=true;s.manifest={version:1,namespace:get("namespace"),fleet_id:get("fleet-id"),generation:s.generation,key:s.key,action:s.action,completions:[]};',
 '}',
 'fs.writeFileSync(sp,JSON.stringify(s));if(fs.existsSync(log+".busy")&&a[0]==="quiesce")process.exit(1);if(fs.existsSync(log+".promotion-fail")&&a[0]==="resume")fs.chmodSync(require("path").join(require("path").dirname(get("config")),"identity.json"),0o400);console.log("fleet-env: "+a[0]+" complete");'
 ].join('\n'));fs.chmodSync(op,0o700);
 exe('docker',[
 'const fs=require("fs"),a=process.argv.slice(2),log=process.env.FIXTURE_LOG,input=JSON.parse(fs.readFileSync(process.env.FIXTURE_INPUT));',
 'if(a[0]!=="--context"||a[1]!==input.context)process.exit(97);a.splice(0,2);fs.appendFileSync(log,"docker "+a.join(" ")+"\\n");',
 'const state=JSON.parse(fs.readFileSync(log+".docker"));const cid=state.replacement?"replacement-id":"control-id";const out=o=>console.log(JSON.stringify(o));',
 'if(a[0]==="info")return out({ID:state.engine_id,OSType:"linux"});',
 'if(a[0]==="container"&&a[1]==="inspect"&&a[2]==="pg-id")return out([{Id:"pg-id",Config:{Labels:{"com.docker.compose.project":"multica","com.docker.compose.service":"postgres"}},State:{Running:true},NetworkSettings:{Networks:{shared:{NetworkID:state.pg_network_id,Aliases:["postgres"]}},Ports:{"5432/tcp":[{HostIp:"127.0.0.1",HostPort:"15432"}]}}}]);',
 'if(a[0]==="network"&&a[1]==="inspect"&&a[2]==="pg-net-id")return out([{Id:state.pg_network_id,Name:"shared",Driver:"bridge",IPAM:{Config:[{Gateway:state.gateway}]},Containers:{"pg-id":{}}}]);',
 'if(a[0]==="image"&&a[1]==="inspect")return out([{Id:"image-id",RepoDigests:[a[2]]}]);',
 'if(a[0]==="run")return console.log(state.socket);',
 'if(a[0]==="network"&&a[1]==="create"){state.network=a[a.length-1];fs.writeFileSync(log+".docker",JSON.stringify(state));return console.log("node-net-id");}',
 'if(a[0]==="network"&&a[1]==="inspect"&&a[2]===state.network)return out([{Id:state.wrong_network_id?"replacement-network":"node-net-id",Name:state.network,Driver:"bridge",Labels:state.labels,Containers:{}}]);',
 'if(a[0]==="ps")return console.log(a.some(v=>v.startsWith("id="))&&a[a.length-1]!=="id="+cid?"":a.join(" ").includes("role=control")?(state.control&&!state.wrong_control?cid:""):(fs.existsSync(log+".orphan")?"orphan-id":state.control?cid:""));',
 'if(a[0]==="volume"&&a[1]==="ls")return console.log("");',
 'if(a[0]==="container"&&a[1]==="start"&&a[2]==="control-id"&&state.control){state.running=true;if(state.replace_on_start)state.replacement=true;if(state.ownership_on_start)state.wrong_project=true;fs.writeFileSync(log+".docker",JSON.stringify(state));return console.log("control-id");}',
 'if(a[0]==="compose"){const cmd=a.slice(a.lastIndexOf("--file")+2);if(!["up","create","start","stop","rm"].includes(cmd[0])||a[a.indexOf("--project-name")+1]!==state.expected_network||cmd[cmd.length-1]!=="fleet")process.exit(97);if(cmd[0]==="create"&&state.control)process.exit(98);if(["start","stop","rm"].includes(cmd[0])){const id=JSON.parse(fs.readFileSync(state.identity));if(!state.control||id.control_id!==cid||id.network_id!=="node-net-id")process.exit(98);}state.control=cmd[0]!=="rm";state.running=["up","start"].includes(cmd[0]);state.created=cmd[0]==="create";fs.writeFileSync(log+".docker",JSON.stringify(state));return;}',
 'if(a[0]==="container"&&a[1]==="inspect"&&a[2]===cid){if(state.timeout_ready&&state.running)Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,31000);const c=JSON.parse(fs.readFileSync(log+".compose")),s=c.services.fleet,l={...s.labels,"com.docker.compose.project":state.wrong_project?"foreign":state.network,"com.docker.compose.service":state.wrong_service?"foreign":"fleet"};if(state.wrong_control)l["multica.fleet.namespace"]="foreign";return out([{Id:cid,Name:state.wrong_name?"/foreign":"/"+state.network+"-control",Config:{Image:s.image,User:s.user,Labels:l,Env:Object.entries(s.environment).map(([k,v])=>k+"="+v),Entrypoint:s.entrypoint,Cmd:s.command.map(v=>v.replaceAll("$$","$")),Healthcheck:{Test:s.healthcheck.test}},HostConfig:{GroupAdd:s.group_add,ReadonlyRootfs:true,Privileged:false,PortBindings:{"8090/tcp":[{HostIp:"127.0.0.1",HostPort:String(state.port)}]}},State:{Running:state.running,Status:state.created?"created":state.running?"running":"exited",Health:{Status:state.unhealthy?"unhealthy":state.starting?(state.starting--,fs.writeFileSync(log+".docker",JSON.stringify(state)),"starting"):"healthy"}},Mounts:s.volumes.map(v=>({Source:v.source,Destination:v.target,RW:!v.read_only})),NetworkSettings:{Networks:{shared:{NetworkID:state.created?"":"pg-net-id"},[state.network]:{NetworkID:state.created?"":"node-net-id"}}}}]);}',
 'if(a[0]==="network"&&a[1]==="ls")return console.log(state.network||"");',
 'if(a[0]==="network"&&a[1]==="rm"){if(fs.existsSync(log+".cleanup-fail"))process.exit(1);state.network=null;fs.writeFileSync(log+".docker",JSON.stringify(state));if(state.crash_before_marker)fs.chmodSync(state.identity,0o400);return console.log(a[2]);}',
 'fs.appendFileSync(log,"UNAPPROVED docker\\n");process.exit(97);'
 ].join('\n'));
 fs.writeFileSync(log+'.docker',JSON.stringify({engine_id:'engine-id',pg_network_id:'pg-net-id',gateway:'172.22.0.1',socket:'0:0:660'}));
 const args=['--repo',repo,'--state',state,'--name',name,'--database-url',db,'--db-name','worktree_test','--api-port','18401','--offset','321','--input',input,'--operator',op];
 const invoke=action=>cp.spawnSync('/bin/bash',[path.join(repo,'scripts/fleet-env.sh'),action,...args],{env,encoding:'utf8',timeout:40000});
 const engine=(k,v)=>{const o=JSON.parse(fs.readFileSync(log+'.docker'));o[k]=v;fs.writeFileSync(log+'.docker',JSON.stringify(o));};
 const change=(k,v)=>{const o=JSON.parse(fs.readFileSync(input));o[k]=v;fs.writeFileSync(input,JSON.stringify(o));};
 const prepare=()=>{const r=invoke('prepare');check(r.status===0,'prepare expected completion, got '+r.stdout.trim()+' '+r.stderr.trim());const id=JSON.parse(fs.readFileSync(path.join(state,'fleet','identity.json')));fs.copyFileSync(path.join(state,'fleet','compose.json'),log+'.compose');engine('port',id.port);engine('expected_network',id.node_network);engine('identity',path.join(state,'fleet','identity.json'));engine('labels',{'multica.fleet.namespace':id.namespace,'multica.fleet.fleet_id':id.fleet_id,'multica.fleet.node':'namespace','multica.fleet.role':'network'});return id;};
 const dev=action=>{fs.writeFileSync(path.join(state,'manifest.env'),'NAME=fixture\n');const script=[
 'source "$FIXTURE_REPO/scripts/dev-env.sh"',
 'resolve_env_for_read() { NAME=fixture; DIR="$FIXTURE_REPO"; REPO_ROOT="$DIR"; STATE_DIR="$FIXTURE_STATE"; BACKEND_PORT=18401; FRONTEND_PORT=13401; DATABASE_URL="$FIXTURE_DSN"; DB_NAME=worktree_test; OFFSET=321; PROFILE=fixture; PROFILE_DIR="$STATE_DIR/profile"; WORKSPACES_ROOT="$STATE_DIR/workspaces"; DESKTOP_APP_SUFFIX=fixture; DESKTOP_USER_DATA_DIR="$STATE_DIR/desktop"; DESKTOP_ENV_FILE="$STATE_DIR/desktop.env"; }',
 'stop_component() { echo "stop $1" >> "$FIXTURE_LOG"; }',
 'start_api() { echo "start api" >> "$FIXTURE_LOG"; }',
 action==='down'?'cmd_down --components api,fleet':'cmd_destroy --yes'
 ].join('\n');return cp.spawnSync('/bin/bash',['-c',script],{encoding:'utf8',timeout:5000,env:{...env,FIXTURE_REPO:repo,FIXTURE_STATE:state,FIXTURE_DSN:db,MULTICA_FLEET_INPUT:input,MULTICA_FLEET_OPERATOR:op}});};
 const api=(mode,template='blank')=>{
  const envFile=path.join(repo,'api.env');fs.writeFileSync(envFile,'DATABASE_URL='+db+'\nMULTICA_LOCAL_FLEET_URL='+(template==='blank'?'':'http://foreign.invalid:19396')+'\nMULTICA_LOCAL_FLEET_SECRET_FILE='+(template==='blank'?'':'/foreign/key')+'\n');
  fs.unlinkSync(path.join(bin,'make'));fs.symlinkSync('/usr/bin/make',path.join(bin,'make'));fs.symlinkSync('/bin/sh',path.join(bin,'sh'));exe('git','console.log("fixture-commit")');
  exe('go','const fs=require("fs");if(process.argv.slice(2).join(" ")!=="run -ldflags -X main.commit=fixture-commit ./cmd/server")process.exit(97);fs.appendFileSync(process.env.FIXTURE_LOG,"api config "+JSON.stringify({url:process.env.MULTICA_LOCAL_FLEET_URL,key:process.env.MULTICA_LOCAL_FLEET_SECRET_FILE})+String.fromCharCode(10));');
  const script=[
   'source "$FIXTURE_REPO/scripts/dev-env.sh"',
   'DIR="$FIXTURE_REPO"; STATE_DIR="$FIXTURE_STATE"; REPO_ROOT="$DIR"; NAME=fixture; BACKEND_PORT=18401; DATABASE_URL="$FIXTURE_DSN"; DB_NAME=worktree_test; OFFSET=321; ENV_FILE="$FIXTURE_ENV"',
   'checkout_commit() { echo fixture-commit; }; pid_file() { echo "$STATE_DIR/api.pid"; }; log_file() { echo "$FIXTURE_LOG"; }',
   'live='+(mode==='cold'?'0':'1'),
   'health_json() { [ "$live" = 1 ] && echo \'{"pid":123,"commit":"fixture-commit","started_at":1}\'; }',
   'component_pid() { [ "$live" = 1 ] && echo 321; }; health_belongs_to_api() { [ "$FIXTURE_MODE" != foreign ]; }; api_identity_matches() { health_belongs_to_api; }; record_component_listener() { echo 123; }; port_listener_pid() { echo 123; }',
   'stop_component() { echo "stop api" >> "$FIXTURE_LOG"; live=0; }; port_free() { [ "$live" = 0 ]; }',
   'launch_detached() { shift; "$@" || exit; live=1; echo 321 > "$STATE_DIR/api.pid"; }',
   'fleet_api_config; start_api; '+(mode==='reuse'?'start_api':mode==='mismatch'?'node -e \'const fs=require("fs"),p=process.argv[1],r=JSON.parse(fs.readFileSync(p));r.configuration="foreign";fs.writeFileSync(p,JSON.stringify(r));\' "$STATE_DIR/api-fleet.json"; start_api':''),
  ].join('\n');
  return cp.spawnSync('/bin/bash',['-c',script],{env:{...env,FIXTURE_REPO:repo,FIXTURE_STATE:state,FIXTURE_DSN:db,FIXTURE_ENV:envFile,FIXTURE_MODE:mode,MULTICA_FLEET_INPUT:input,MULTICA_FLEET_OPERATOR:op},encoding:'utf8',timeout:5000});
 };
 const entryPrepare=()=>cp.spawnSync('/bin/bash',['-c','source "$FIXTURE_REPO/scripts/dev-env.sh"; NAME="$FIXTURE_NAME"; DIR="$FIXTURE_REPO"; STATE_DIR="$FIXTURE_STATE"; DATABASE_URL="$FIXTURE_DSN"; DB_NAME=worktree_test; BACKEND_PORT=18401; OFFSET=321; fleet_action prepare'],{env:{...env,FIXTURE_REPO:repo,FIXTURE_NAME:name,FIXTURE_STATE:state,FIXTURE_DSN:db,MULTICA_FLEET_INPUT:input,MULTICA_FLEET_OPERATOR:op},encoding:'utf8',timeout:5000});
 return {dir,repo,state,home,log,input,db,env,invoke,prepare,change,engine,profiles,key,profile,dev,api,entryPrepare};
}
test('TestAnthropicPathPrefixPreserved',()=>{
 for(const url of ['https://ark.cn-beijing.volces.com/api/plan','https://provider.invalid','https://provider.invalid/v1/messages-test_~;=+$&(),!','https://provider.invalid/percent%25']){
  const f=fixture(),input=JSON.parse(fs.readFileSync(f.input));input.aurora.anthropic_base_url=url;f.change('aurora',input.aurora);f.prepare();
  check(JSON.parse(fs.readFileSync(f.input)).aurora.anthropic_base_url===url,'descriptor URL changed');
  check(JSON.parse(fs.readFileSync(path.join(f.state,'fleet','config.json'))).aurora.anthropic_base_url===url,'config lost URL prefix');
 }
});
test('TestAnthropicInvalidURLsDeniedBeforeExternalCommands',()=>{
 for(const url of ['http://provider.invalid/api/plan','https://user:pass@provider.invalid/api/plan','https://@provider.invalid/api/plan','https://provider.invalid:443/api/plan','https://provider.invalid:8443/api/plan','https://provider.invalid/api/plan?x=1','https://provider.invalid/api/plan?','https://provider.invalid/api/plan#x','https://provider.invalid/api/plan#',' https://provider.invalid','https://provider.invalid'+String.fromCharCode(10),'https://pro	vider.invalid/api/plan','https://provider.invalid/api plan','https://provider.invalid/','https://provider.invalid/api/','https://provider.invalid/api//plan','https://provider.invalid/api/../plan','https://provider.invalid/./plan','https://provider.invalid/%61pi/plan','https://provider.invalid/api%2Fplan','https://provider.invalid/api%20plan','https://provider.invalid/%zz','https://provider.invalid/api'+String.fromCharCode(92)+'plan','https://provider.invalid,other/api/plan']){
  const f=fixture(),input=JSON.parse(fs.readFileSync(f.input));input.aurora.anthropic_base_url=url;f.change('aurora',input.aurora);
  const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'invalid URL accepted: '+JSON.stringify(url));check(fs.readFileSync(f.log,'utf8')==='','external commands reached on invalid URL');
 }
});
test('TestServerURLStillRejectsPathPrefix',()=>{
 const f=fixture(),input=JSON.parse(fs.readFileSync(f.input));input.aurora.server_url='https://multica.example.com/api/plan';f.change('aurora',input.aurora);
 const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'server path prefix accepted');check(fs.readFileSync(f.log,'utf8')==='','external commands reached on invalid server URL');
});
test('TestExclusiveManagedDatabaseOwnershipRequired',()=>{for(const kind of ['missing','mismatched','borrowed']){const f=fixture();f.prepare();const freshIdentity=path.join(f.state,'fleet','identity.json');check(fs.realpathSync(freshIdentity)===freshIdentity,'fixture reset target was not canonical');const existingIdentity=fs.readFileSync(freshIdentity);fs.unlinkSync(freshIdentity);const before=fs.readFileSync(f.log,'utf8');if(kind==='missing'){const input=JSON.parse(fs.readFileSync(f.input));delete input.database_lifecycle;fs.writeFileSync(f.input,JSON.stringify(input));}else if(kind==='mismatched')f.change('database_name','foreign');else f.change('database_lifecycle','borrowed');const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),kind+' DB ownership accepted');check(fs.readFileSync(f.log,'utf8')===before,'operator/SQL/cleanup reached after '+kind+' ownership');fs.writeFileSync(freshIdentity,existingIdentity,{mode:0o600});const down=f.dev('down');check(down.status!==0&&!fs.readFileSync(f.log,'utf8').includes('stop api'),'API/data stopped on ownership denial');check(fs.existsSync(path.join(f.state,'manifest.env')),'registry removed on ownership denial');}});
test('TestSharedPGNetworkURLPreservesDatabaseAndOptions',()=>{const f=fixture(),id=f.prepare();check(fs.readFileSync(path.join(f.state,'fleet','database-url'),'utf8')===f.db.replace('127.0.0.1:15432','postgres:5432'),'DSN identity/options changed');check(JSON.parse(fs.readFileSync(path.join(f.state,'fleet','config.json'))).api_url==='http://host.docker.internal:18401','API URL changed');check(f.prepare().fleet_id===id.fleet_id,'identity changed on retry');});
test('TestLinuxLoopbackPGIsNotGateway',()=>{const f=fixture();f.prepare();const before=fs.readFileSync(f.log,'utf8');f.engine('gateway','127.0.0.1');const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'loopback gateway accepted');check(fs.readFileSync(f.log,'utf8').split('operator ').length===before.split('operator ').length,'operator invoked on invalid network');});
test('TestNodesDoNotJoinPGNetwork',()=>{const f=fixture(),id=f.prepare(),c=JSON.parse(fs.readFileSync(path.join(f.state,'fleet','compose.json')));check(c.services.fleet.networks.length===2,'Fleet missing networks');check(c.networks['fleet-nodes'].name===id.node_network&&id.node_network!=='shared','node network aliases PG');check(Object.keys(c.services).join()==='fleet','unexpected node/PG service');});
test('TestAuroraProfileUsesDirectNetworkingAndSandboxSpec',()=>{const f=fixture(),id=f.prepare(),c=JSON.parse(fs.readFileSync(path.join(f.state,'fleet','config.json')));check(c.specs&&c.specs.sandbox&&Object.keys(c.specs).join()==='sandbox','sandbox spec missing');check(c.aurora&&c.aurora.uplink_network===undefined&&c.aurora.egress_hosts===undefined&&c.aurora.egress_pins===undefined,'retired egress config remains');check(c.aurora.readonly_rootfs===true,'aurora hardening lost');check(c.aurora.proxy_image===undefined&&c.aurora.seccomp_profile===undefined&&c.aurora.apparmor_profile===undefined&&c.aurora.provider_secret_files===undefined,'retired aurora keys carried into the config');});
test('TestAuroraRetiredKeysDeniedBeforeOperator',()=>{
 // The Aurora profile no longer carries an egress image, a seccomp profile, an
 // AppArmor profile or provider secret files; the strict key set refuses them.
 for(const retired of [{egress_hosts:[]},{egress_pins:{}},{uplink_network:"old-uplink"},{proxy_image:'ghcr.io/eanfs/multica-aurora-egress:latest'},{seccomp_profile:'/etc/multica/aurora/seccomp.json'},{apparmor_profile:'multica-aurora-sandbox'},{provider_secret_files:{'anthropic-api-key':'/etc/multica/aurora/anthropic-api-key'}}]) {
  const g=fixture();const i=JSON.parse(fs.readFileSync(g.input));Object.assign(i.aurora,retired);fs.writeFileSync(g.input,JSON.stringify(i));
  const r=g.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'retired aurora key accepted: '+JSON.stringify(retired));
  check(!fs.readFileSync(g.log,'utf8').includes('operator '),'operator invoked before aurora validation: '+JSON.stringify(retired));
 }
});
test('TestAuroraProviderEnvCarriedAndOtherCredentialDenied',()=>{const f=fixture(),id=f.prepare(),c=JSON.parse(fs.readFileSync(path.join(f.state,'fleet','config.json')));check(c.aurora.claude_env&&c.aurora.claude_env['ANTHROPIC_DEFAULT_SONNET_MODEL']==='glm-5.3-flash[1M]'&&c.aurora.claude_env['API_TIMEOUT_MS']==='600000','claude_env not carried into the config');check(id.fleet_id&&c.aurora.uplink_network===undefined,'prepare identity changed');const g=fixture();const input=JSON.parse(fs.readFileSync(g.input));input.aurora.claude_env={ANTHROPIC_API_KEY:'ark-key',VOLC_ASR_API_KEY:'asr-key'};fs.writeFileSync(g.input,JSON.stringify(input));g.prepare();const carried=JSON.parse(fs.readFileSync(path.join(g.state,'fleet','config.json')));check(carried.aurora.claude_env.ANTHROPIC_API_KEY==='ark-key'&&carried.aurora.claude_env.VOLC_ASR_API_KEY==='asr-key','provider credentials not carried');const d=fixture();const bad=JSON.parse(fs.readFileSync(d.input));bad.aurora.claude_env={ARK_API_KEY:'secret'};fs.writeFileSync(d.input,JSON.stringify(bad));const r=d.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'non-provider credential claude_env accepted');check(!fs.readFileSync(d.log,'utf8').includes('operator '),'operator invoked before claude_env validation');});
test('TestAuroraClaudeEnvUnknownOrBadValueDenied',()=>{for(const claudeEnv of [{CLAUDE_CODE_UNKNOWN:'x'},{ENABLE_TOOL_SEARCH:'true '},{API_TIMEOUT_MS:'soon'}]){const f=fixture();f.prepare();const before=fs.readFileSync(f.log,'utf8'),input=JSON.parse(fs.readFileSync(f.input));input.aurora.claude_env=claudeEnv;fs.writeFileSync(f.input,JSON.stringify(input));const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'bad claude_env accepted: '+JSON.stringify(claudeEnv));check(fs.readFileSync(f.log,'utf8').split('operator ').length===before.split('operator ').length,'operator invoked before claude_env validation');}});
test('TestAuroraUnknownKeyDeniedBeforeOperator',()=>{const f=fixture();const input=JSON.parse(fs.readFileSync(f.input));input.aurora.evil_key='x';fs.writeFileSync(f.input,JSON.stringify(input));const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'unknown aurora key accepted');check(!fs.readFileSync(f.log,'utf8').includes('operator '),'operator invoked before aurora validation');});
for(const [name,mutate] of [
 ['TestWrongPGOwnershipDenied',f=>f.engine('engine_id','foreign')],
 ['TestMissingPGNetworkDenied',f=>f.engine('pg_network_id','foreign')],
 ['TestWrongSocketGroupDenied',f=>f.engine('socket','0:999:660')],
 ['TestRootFleetUIDDenied',f=>f.change('uid',0)],
 ['TestWrongFleetGIDDenied',f=>f.change('gid',999)],
 ['TestMalformedProfileMapDenied',f=>fs.writeFileSync(f.profiles,JSON.stringify({version:1,owners:{bad:f.profile}}))],
 ['TestPublicPrivateFileDenied',f=>fs.chmodSync(f.key,0o644)]
])test(name,()=>{const f=fixture();f.prepare();const before=fs.readFileSync(f.log,'utf8');mutate(f);const r=f.invoke('prepare');check(r.status!==0&&r.stdout.includes('denied'),'expected denial');check(fs.readFileSync(f.log,'utf8').split('operator ').length===before.split('operator ').length,'operator invoked before validation');if(name==='TestPublicPrivateFileDenied'){fs.chmodSync(f.key,0o600);fs.chmodSync(f.dir,0o755);const directoryDenial=f.invoke('prepare');check(directoryDenial.status!==0,'public private directory accepted');}});
test('TestOperatorChildOmitsParentHOMEAndPG',()=>{const f=fixture();f.prepare();check(fs.readFileSync(f.log,'utf8').includes('operator prepare'),'operator not invoked');check(f.env.HOME===f.home&&f.env.PGSSLCERT,'parent contract changed');});
test('TestUpStatusDownResumeRetainsIdentityAndData',()=>{const f=fixture(),id=f.prepare();const closureKeys=[];for(const action of ['up','status','down','up','down','up']){if(action==='down')closureKeys.push(JSON.parse(fs.readFileSync(path.join(f.state,'fleet','identity.json'))).operation_key);const r=f.invoke(action);check(r.status===0,action+' denied: '+r.stdout+' '+r.stderr);}check(closureKeys.length===2&&closureKeys[0]!==closureKeys[1],'two cycles reused a closure key');check(JSON.parse(fs.readFileSync(path.join(f.state,'fleet','identity.json'))).fleet_id===id.fleet_id,'resume changed identity');const log=fs.readFileSync(f.log,'utf8');check(log.includes('operator quiesce')&&log.includes('operator resume'),'operator lifecycle omitted');check(!log.includes('UNAPPROVED')&&!log.includes('volume rm'),'down removed data or used unapproved action');});
test('TestWrongControlOwnershipDeniesBeforeAPIStop',()=>{for(const kind of ['wrong_control','wrong_project','wrong_service','wrong_name','replacement','wrong_network_id']){const f=fixture();f.prepare();check(f.invoke('up').status===0,'up baseline failed');f.engine(kind,true);const before=fs.readFileSync(f.log,'utf8');const r=f.dev('down');check(r.status!==0,kind+' foreign control accepted');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(!after.includes('stop api')&&!after.includes('container start'),'API stopped/control started on foreign control');}const f=fixture(),id=f.prepare();f.engine('network',id.node_network);f.engine('control',true);f.engine('running',true);const before=fs.readFileSync(f.log,'utf8');check(f.dev('down').status!==0&&f.invoke('up').status!==0,'copied labels adopted without creation CID');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(!after.includes('stop api')&&!after.includes('container start')&&!after.includes('compose --'),'unrecorded candidate received lifecycle operation');});
test('TestFleetPortAvoidsForeignListener',()=>{const f=fixture();f.engine('port_busy',true);const id=f.prepare();check(id.port!==19321,'allocated a foreign occupied port');check(f.prepare().port===id.port,'port changed on retry');});
test('TestExistingDBMigrationPrecedesOperator',()=>{const f=fixture();f.prepare();const log=fs.readFileSync(f.log,'utf8');check(log.indexOf('migration complete')>=0&&log.indexOf('migration complete')<log.indexOf('operator prepare'),'operator used DB before migration');fs.writeFileSync(f.log+'.migration-fail','');const before=log.split('operator ').length;const r=f.invoke('prepare');check(r.status!==0,'failed migration accepted');check(fs.readFileSync(f.log,'utf8').split('operator ').length===before,'operator called after failed migration');});
test('TestPrivateDSNNotSerializedOrPrinted',()=>{const f=fixture();f.prepare();const raw=fs.readFileSync(path.join(f.state,'fleet','compose.json'),'utf8');check(!raw.includes(f.db)&&!raw.includes('p%40ss'),'DSN serialized');check(raw.includes('$$DATABASE_URL'),'Compose would interpolate DSN');const r=f.invoke('status');check(!r.stdout.includes('p%40ss')&&!r.stderr.includes('fixture-only'),'private input printed');});
test('TestFailedResumeKeepsOriginalClosureKey',()=>{const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');const before=fs.readFileSync(path.join(f.state,'fleet','identity.json'),'utf8');fs.writeFileSync(f.log+'.resume-fail','');check(f.invoke('up').status!==0,'failed resume accepted');check(fs.readFileSync(path.join(f.state,'fleet','identity.json'),'utf8')===before,'failed resume changed key/identity');});
test('TestRepeatedUpDeniesWithoutNewClosureOrKey',()=>{const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0&&f.invoke('up').status===0,'cycle baseline failed');const before=fs.readFileSync(path.join(f.state,'fleet','identity.json'),'utf8'),count=fs.readFileSync(f.log,'utf8').split('operator quiesce').length;check(f.invoke('up').status!==0,'open namespace conflict hidden');check(fs.readFileSync(path.join(f.state,'fleet','identity.json'),'utf8')===before,'repeat up changed identity');check(fs.readFileSync(f.log,'utf8').split('operator quiesce').length===count,'repeat up created repair closure');});
test('TestUncertainResumePromotionDeniesAndKeepsOriginalKey',()=>{const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');const p=path.join(f.state,'fleet','identity.json'),before=fs.readFileSync(p,'utf8');fs.writeFileSync(f.log+'.promotion-fail','');check(f.invoke('up').status!==0,'uncertain promotion reported completion');check(fs.readFileSync(p,'utf8')===before,'uncertain promotion changed original key');fs.chmodSync(p,0o600);fs.unlinkSync(f.log+'.promotion-fail');check(f.invoke('up').status!==0,'uncertain open state inferred as success');});
// Original proof denial must preserve the durable fence and every recovery input.
function proofSnapshot(f){const files={};const visit=p=>{const s=fs.lstatSync(p);if(s.isDirectory()){files[p]={mode:s.mode&511};for(const n of fs.readdirSync(p).sort())visit(path.join(p,n));}else files[p]={mode:s.mode&511,bytes:fs.readFileSync(p).toString('base64')};};for(const p of [f.state,f.input,f.profiles,f.profile,f.key,f.log+'.operator-state',f.log+'.docker'])visit(p);return JSON.stringify(files);}
function originalProofBranches(stopped){const failures=[];for(const kind of ['missing','null','corrupt','key','epoch','action','version','namespace','fleet-id','missing-completions','null-completions']){const f=fixture();f.prepare();if(stopped)check(f.invoke('up').status===0&&f.invoke('down').status===0,'Stop proof baseline failed');else check(f.invoke('destroy').status===0,'Delete proof baseline failed');fs.writeFileSync(path.join(f.state,'manifest.env'),'NAME=fixture\n');const sp=f.log+'.operator-state',s=JSON.parse(fs.readFileSync(sp));if(kind==='missing')delete s.manifest;else if(kind==='null')s.manifest=null;else if(kind==='corrupt')s.manifest='not a manifest';else if(kind==='missing-completions')delete s.manifest.completions;else if(kind==='null-completions')s.manifest.completions=null;else s.manifest[{'epoch':'generation','fleet-id':'fleet_id'}[kind]||kind]=kind==='epoch'?s.generation+1:kind==='version'?2:kind==='action'?(stopped?'delete':'stop'):'foreign';fs.writeFileSync(sp,JSON.stringify(s));const before=fs.readFileSync(f.log,'utf8'),inputs=proofSnapshot(f),r=f.dev('destroy'),after=fs.readFileSync(f.log,'utf8').slice(before.length);try{check(r.status!==0,kind+' original '+(stopped?'Stop':'Delete')+' proof accepted');check(!/start api|stop api|stop (fleet|web|desktop)|container start|compose --|network rm|UNAPPROVED|operator resume/.test(after),kind+' proof denial mutated API/resources/DB');check(proofSnapshot(f)===inputs,kind+' proof denial changed epoch/key/manifest/private inputs/registry');}catch(e){failures.push(e.message);}}check(failures.length===0,failures.join('; '));}
test('TestStoppedDestroyRestartsOwnedControlWithoutResume',()=>{originalProofBranches(true);const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');
 const sp=f.log+'.operator-state',s=JSON.parse(fs.readFileSync(sp));check(s.action==='stop'&&Array.isArray(s.manifest.completions)&&s.manifest.completions.length===0,'valid original empty Stop proof missing');s.manifest=Object.fromEntries(Object.entries(s.manifest).reverse());fs.writeFileSync(sp,JSON.stringify(s));const original=fs.readFileSync(sp,'utf8');check(f.invoke('quiesce').status===0&&fs.readFileSync(sp,'utf8')===original,'Stop replay reconstructed original proof');
 const before=fs.readFileSync(f.log,'utf8'),r=f.dev('destroy'),after=fs.readFileSync(f.log,'utf8').slice(before.length);check(after.includes('operator destroy'),'destroy not reached');const next=JSON.parse(fs.readFileSync(sp));check(next.generation===s.generation+1&&next.key===s.key&&next.action==='delete'&&next.manifest.action==='delete'&&next.manifest.completions.length===0,'valid original Stop did not transition to completed Delete');check(after.indexOf('start api')<after.indexOf('container start control-id')&&after.indexOf('container start control-id')<after.indexOf('operator destroy'),'restart order wrong');check(!after.includes('operator resume'),'destroy reopened admission');check(!after.includes('UNAPPROVED'),'unapproved command attempted');});
test('BusyKeepsAPI',()=>{const f=fixture();f.prepare();fs.writeFileSync(f.log+'.busy','');const r=f.dev('down');check(r.status!==0,'busy down succeeded');check(fs.readFileSync(f.log,'utf8').includes('operator quiesce'),'closure was not attempted');check(!fs.readFileSync(f.log,'utf8').includes('stop api'),'API stopped on busy');check(fs.existsSync(path.join(f.state,'manifest.env')),'registry removed');});
test('TestCompletedCleanupRetryChecksOriginalCycleAndCurrentAbsence',()=>{
 originalProofBranches(false);
const f=fixture();f.prepare();check(f.invoke('destroy').status===0,'first owned cleanup denied');const sp=f.log+'.operator-state',s=JSON.parse(fs.readFileSync(sp));s.manifest=Object.fromEntries(Object.entries(s.manifest).reverse());fs.writeFileSync(sp,JSON.stringify(s));
 const original=fs.readFileSync(sp,'utf8'),count=fs.readFileSync(f.log,'utf8').split('operator destroy').length;check(f.invoke('destroy').status===0,'completed cleanup retry denied');check(fs.readFileSync(f.log,'utf8').split('operator destroy').length===count+1,'original SQL cycle not rechecked');check(fs.readFileSync(sp,'utf8')===original,'same-action replay reconstructed original proof');fs.writeFileSync(f.log+'.orphan','');check(f.invoke('destroy').status!==0,'orphan accepted after completed cleanup');
 for(const kind of ['key','epoch','original-proof','replacement']){const f=fixture();f.prepare();check(f.invoke('destroy').status===0,'cleanup baseline denied');const ip=path.join(f.state,'fleet','identity.json');if(kind==='key'){const id=JSON.parse(fs.readFileSync(ip));id.operation_key='99999999-9999-4999-8999-999999999999';id.cleanup_intent_key=id.operation_key;id.cleanup_operation_key=id.operation_key;fs.writeFileSync(ip,JSON.stringify(id));}else if(kind==='epoch'){const op=JSON.parse(fs.readFileSync(f.log+'.operator-state'));op.generation++;fs.writeFileSync(f.log+'.operator-state',JSON.stringify(op));}else if(kind==='original-proof'){const op=JSON.parse(fs.readFileSync(f.log+'.operator-state'));op.manifest=null;fs.writeFileSync(f.log+'.operator-state',JSON.stringify(op));}else{f.engine('control',true);f.engine('network',JSON.parse(fs.readFileSync(ip)).node_network);f.engine('replacement',true);}const before=fs.readFileSync(f.log,'utf8');check(f.invoke('destroy').status!==0,kind+' completion retry accepted');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(!after.includes('container start')&&!after.includes('compose --')&&!after.includes('network rm'),'failed original proof/replaced inventory mutated resources');}});
test('FailedResourceCleanupKeepsDBRegistry',()=>{const f=fixture();f.prepare();fs.writeFileSync(f.log+'.cleanup-fail','');const r=f.dev('destroy');check(r.status!==0,'failed cleanup succeeded');check(!fs.readFileSync(f.log,'utf8').includes('UNAPPROVED'),'DB cleanup attempted');check(fs.existsSync(path.join(f.state,'manifest.env')),'registry removed');fs.unlinkSync(f.log+'.cleanup-fail');const before=fs.readFileSync(f.log,'utf8');f.dev('destroy');check(JSON.parse(fs.readFileSync(path.join(f.state,'fleet','identity.json'))).cleanup_operation_key===JSON.parse(fs.readFileSync(path.join(f.state,'fleet','identity.json'))).operation_key,'finalized Delete native cleanup retry denied');check(f.invoke('destroy').status===0,'original Delete helper replay denied');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(after.includes('operator destroy')&&!after.includes('operator quiesce')&&!after.includes('container start')&&!after.includes('start api'),'retry used Stop/restart instead of original Delete');});
test('TestManagedAPIMakeAssignmentsAndReuse',()=>{for(const template of ['blank','foreign']){const f=fixture(),id=f.prepare(),r=f.api('cold',template);check(r.status===0,'API launch fixture failed: '+r.stderr);const log=fs.readFileSync(f.log,'utf8');check(log.includes('"url":"http://127.0.0.1:'+id.port+'"')&&log.includes('"key":"'+f.state+'/fleet/service-key"'),'ENV_FILE overrides managed API configuration');}for(const mode of ['owned','reuse','mismatch','foreign']){const f=fixture();f.prepare();const r=f.api(mode),log=fs.readFileSync(f.log,'utf8');if(mode==='foreign')check(r.status!==0&&!log.includes('stop api')&&!log.includes('api config'),'foreign listener adopted/stopped');else{check(r.status===0,'owned API denied: '+r.stderr);check(log.includes('operator quiesce')&&log.indexOf('operator quiesce')<log.indexOf('stop api'),'owned non-Fleet API reused or stopped before closure');check(log.split('api config').length===(mode==='mismatch'?3:2),'managed API reuse ignored composition');}}const f=fixture();f.prepare();fs.writeFileSync(f.log+'.busy','');check(f.api('owned').status!==0,'failed Stop allowed API restart');const log=fs.readFileSync(f.log,'utf8');check(!log.includes('stop api')&&!log.includes('api config'),'API mutated before trusted closure');});
test('TestRegistryNamesRetainAllocatedIdentity',()=>{for(const name of ['local_docker_cloud_runtime-321','explicit_under_score','a'.repeat(128)]){const f=fixture(name);check(f.entryPrepare().status===0,'managed name entry denied');const id=f.prepare();check(id.name===name&&f.prepare().port===id.port,'name/slot changed');}for(const name of ['../bad','A','a/b','a\n','a'.repeat(129)]){const f=fixture(name);check(f.entryPrepare().status!==0&&f.invoke('prepare').status!==0,'invalid name accepted');}});
test('TestStoppedControlReadinessWaitsAndDeniesUnhealthy',()=>{for(const unhealthy of [false,true]){const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');f.engine(unhealthy?'unhealthy':'starting',unhealthy?true:20);const before=fs.readFileSync(f.log,'utf8'),r=f.invoke('destroy'),after=fs.readFileSync(f.log,'utf8').slice(before.length);check(unhealthy?r.status!==0:r.status===0,'readiness outcome wrong');check(!after.includes('operator resume'),'destroy resumed');if(unhealthy)check(!after.includes('operator destroy')&&fs.existsSync(path.join(f.state,'fleet','identity.json')),'unhealthy destroy lost recovery');}});
test('TestCleanupIntentNeverAuthorizesSQLOrRestart',()=>{for(const forged of [false,true]){const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');fs.writeFileSync(f.log+'.destroy-fail','');const ip=path.join(f.state,'fleet','identity.json');if(forged){const id=JSON.parse(fs.readFileSync(ip));id.cleanup_intent_key=id.operation_key;fs.writeFileSync(ip,JSON.stringify(id));}check(f.invoke('destroy').status!==0,'failed SQL destroy accepted');const before=fs.readFileSync(f.log,'utf8'),inputs=fs.readFileSync(ip,'utf8');check(f.invoke('destroy').status!==0,'intent inferred SQL success');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(after.includes('operator destroy')&&!after.includes('operator quiesce')&&!after.includes('container start')&&!after.includes('network rm')&&fs.readFileSync(ip,'utf8')===inputs,'intent authorized restart/cleanup or changed recovery');}});
test('TestNetworkRemovedBeforeCleanupMarkerRetry',()=>{const f=fixture();f.prepare();check(f.invoke('up').status===0,'up baseline failed');f.engine('crash_before_marker',true);check(f.invoke('destroy').status!==0,'interrupted marker promotion succeeded');const ip=path.join(f.state,'fleet','identity.json');check(JSON.parse(fs.readFileSync(ip)).cleanup_operation_key===undefined&&JSON.parse(fs.readFileSync(f.log+'.docker')).network===null,'crash not after network removal');fs.chmodSync(ip,0o600);const before=fs.readFileSync(f.log,'utf8');check(f.invoke('destroy').status===0,'absent owned network retry denied');const after=fs.readFileSync(f.log,'utf8').slice(before.length);check(after.includes('operator destroy')&&!after.includes('operator quiesce')&&!after.includes('container start'),'absent network retry fabricated restart authority');});
test('TestReadinessTimeoutOrReplacementPreservesInputs',()=>{for(const kind of ['timeout_ready','replace_on_start','ownership_on_start']){const f=fixture();f.prepare();check(f.invoke('up').status===0&&f.invoke('down').status===0,'cycle baseline failed');const ip=path.join(f.state,'fleet','identity.json'),inputs=fs.readFileSync(ip,'utf8');f.engine(kind,true);const before=fs.readFileSync(f.log,'utf8'),start=Date.now(),r=f.invoke('destroy'),after=fs.readFileSync(f.log,'utf8').slice(before.length);check(r.status!==0,kind+' accepted');check(Date.now()-start<38000,'ordinary Docker deadline exceeded');check(!after.includes('operator destroy')&&!after.includes('operator resume')&&fs.readFileSync(ip,'utf8')===inputs,'readiness denial lost inputs or resumed');}});
console.log('Fleet behavioral cases: '+passed+' PASS, '+failed+' FAIL, 0 SKIP');process.exitCode=failed?1:0;
NODE
